### ISSUE TITLE
List of tasks to be done

### ISSUE THREAD

**Issue by behzadhaki** [behzadhaki/MonotonicGrooveTransformer#5]
#### Todo
- [x] Implement an internal multi-layer drum synth
- [x] Implement a simple piano synth to minimize DAW involvement for testing
- [x] Modify the patch such that the starting point of the sequence is modifiable (super helpful to inspect the capabilities of the model to generalize beyond fixed phase)

- [ ] Think about how better update the groove over time as more onsets are received
- [ ] Implement a midi looper w/ overdub capability
- [ ] Extend patch to work with audio inputs as well:
   - [ ] Implement a simple audio onset/velocity detector using bonk~ in pd
   - [ ] Implement a simple looper with overdub capabilities
- [ ] Think about alternative ways of sampling and better controllability of generations

**Comment by behzadhaki** [comment]
Finished 
- [x] Implement an internal multi-layer drum synth
- [x] Implement a simple piano synth to minimize DAW involvement for testing

**Comment by behzadhaki** [comment]
Finished

- [x] Modify the patch such that the starting point of the sequence is modifiable (super helpful to inspect the capabilities of the model to generalize beyond fixed phase)
